### ISSUE TITLE
RemoveRepetition transformer behavior

### ISSUE THREAD

**Issue by morswin22** [morswin22/TextTransformer#1]
We need to decide what is the correct behavior for removing repetitions in cases like this one:

https://github.com/morswin22/TextTransformer/blob/0e82a448cdff55f43388b86cc654187f216f144c/src/test/java/pl/put/poznan/transformer/logic/RemoveRepetitionTest.java#L23

Please comment whether you think that the current behavior is correct or write your suggestion on how it should behave.

**Comment by Strajkerr** [comment]
I agree with current behaviour :)

**Comment by markopolo139** [comment]
I think that correct behavior for this case is that Transformer wouldn't delete any text so result would be "jest: jest! jest."

**Comment by MBernart** [comment]
I agree with @markopolo139. The text should be deleted only if it's separated by whitespace. 
For example, a message like: 
`remove text: text should be trimmed`
should not be changed
